import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
    <Head>
      <title>Seoyoung JEEEEEE</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
      <div className={styles.top}>
        <h1 className={styles.title}>SEOYOUNG</h1>
        <p className={styles.p}>Welcome To My Website \o/</p>
      </div>

      <div>
        <div className={styles.Nav}>
          <div className={styles.navName}><a href=''><h3>About me</h3></a></div>
          <div className={styles.navName}><a href=''><h3>Home</h3></a></div>
          <div className={styles.navName}><a href=''><h3>Skill</h3></a></div>
        </div>
        <div className={styles.article}>
          <div className={styles.ImageContainer}>
            <img className={styles.homeImage} src='/imgs/profile2.png'></img>
          </div>
        </div>
      </div>

      <div>
        <div className={styles.contactT}>
          <h2>CONTACT</h2>
        </div>
        
        <div className={styles.contact}>
          <div className={styles.ImageContainer}>
            <a href='https://www.instagram.com/__seoyoung.____/?hl=ko' target="_blank" rel="noopener noreferrer">
              <img className={styles.contactIMG} src='/imgs/instagram.png'></img></a>
          </div>
          <div className={styles.ImageContainer}>
            <a href=''><img className={styles.contactIMG} src='/imgs/facebook.png'></img></a>
          </div>
          <div className={styles.ImageContainer}>
            <a href='https://github.com/JeeSeoyoung' target="_blank" rel="noopener noreferrer">
              <img className={styles.contactIMG} src='/imgs/github.png'></img></a>
          </div>
        </div>
      </div>
    </div>
  )
}
