import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Top from '../Components/Top';
import Body from '../Components/Body';
import Footer from '../Components/Footer';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Seoyoung JEEEEEE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body></Body>
    </div>
  )
}



